#!/bin/bash

# setup-environment.sh (Gemini CLI)
# Installs the obsidian-vault-mcp v2 Gemini extension and configures this vault.
#
# v2 ships as an npm package, so there is no longer a clone/build step: the
# extension manifest launches the server through npx.

set -euo pipefail

REPO_ROOT=$(git rev-parse --show-toplevel 2>/dev/null || pwd)
EXT_REPO_URL="https://github.com/jabez007/obsidian-vault-mcp"
EXT_NAME="obsidian-vault-mcp"
LEGACY_EXT_NAME="gemini-obsidian"

echo "--- 1. Dependency checks ---"
for cmd in git jq node npx gemini; do
  if ! command -v "$cmd" >/dev/null 2>&1; then
    echo "Error: '$cmd' is required but not installed."
    exit 1
  fi
done
echo "Required commands found."

echo "--- 2. Installing the $EXT_NAME extension ---"
EXT_LIST=$(gemini extensions list 2>&1 || true)

if grep -q "$LEGACY_EXT_NAME" <<<"$EXT_LIST" && ! grep -q "$EXT_NAME" <<<"$EXT_LIST"; then
  echo "Found the legacy '$LEGACY_EXT_NAME' extension. Removing it before installing v2..."
  gemini extensions uninstall "$LEGACY_EXT_NAME" || \
    echo "Warning: could not uninstall '$LEGACY_EXT_NAME'. Remove it manually if both remain installed."
fi

if grep -q "$EXT_NAME" <<<"$EXT_LIST"; then
  echo "Extension '$EXT_NAME' already installed. Updating..."
  gemini extensions update "$EXT_NAME" || echo "Note: update skipped or already current."
else
  gemini extensions install "$EXT_REPO_URL" --consent
fi

echo "--- 3. Configuring vault ---"
bash "$REPO_ROOT/scripts/configure-vault.sh"

echo "--- 4. Generating per-harness assets ---"
bash "$REPO_ROOT/scripts/sync-assets.sh"

echo "--- 5. Installing the global Agent Memory SessionStart hook ---"
# Installed globally so Agent Memory restores in any directory, not just this
# repo. The context body is copied from the canonical repo script so the global
# hook and the repo-local harness hooks cannot drift apart.
GLOBAL_HOOKS_DIR="$HOME/.gemini/hooks"
GLOBAL_SETTINGS_JSON="$HOME/.gemini/settings.json"
CONTEXT_TARGET="$GLOBAL_HOOKS_DIR/agent-memory-context.sh"
HOOK_SCRIPT="$GLOBAL_HOOKS_DIR/agent-memory-boot.sh"

mkdir -p "$GLOBAL_HOOKS_DIR"
cp "$REPO_ROOT/scripts/agent-memory-context.sh" "$CONTEXT_TARGET"
chmod +x "$CONTEXT_TARGET"

cat >"$HOOK_SCRIPT" <<EOF
#!/bin/bash
# Hook: SessionStart — injects Agent Memory SOPs and restores session state.
# Generated by johnny-decimal-zettelkasten/.gemini/setup-environment.sh.
# Edit scripts/agent-memory-context.sh in that repo and re-run setup instead.

set -euo pipefail

CONTEXT=\$(bash "$CONTEXT_TARGET" 2>/dev/null || echo "Agent Memory: context script failed.")

jq -n --arg context "\$CONTEXT" \\
      --arg msg "Agent Memory: SOPs and Activity Map restored." \\
      '{"systemMessage": \$msg, "hookSpecificOutput": {"additionalContext": \$context}}'
EOF

chmod +x "$HOOK_SCRIPT"

echo "Registering the hook in $GLOBAL_SETTINGS_JSON..."
if [ ! -f "$GLOBAL_SETTINGS_JSON" ]; then
  echo '{}' >"$GLOBAL_SETTINGS_JSON"
fi

TEMP_SETTINGS=$(mktemp)
trap 'rm -f "$TEMP_SETTINGS"' EXIT
jq --arg name "agent-memory-boot" \
  --arg script "$HOOK_SCRIPT" \
  '.hooks |= (. // {})
   | .hooks.SessionStart |= (. // [])
   | if any(.hooks.SessionStart[]; (.hooks? // []) | any(.[]; .name == $name)) then
       # Already registered: refresh the command path in case the repo moved.
       # Only touch entries that actually carry a hooks array; mapping over a
       # missing key makes jq fail with "Cannot iterate over null".
       .hooks.SessionStart |= map(
         if (.hooks | type) == "array" then
           .hooks |= map(if .name == $name then .command = $script else . end)
         else . end
       )
     else
       .hooks.SessionStart += [{"matcher": "*", "hooks": [{"name": $name, "type": "command", "command": $script}]}]
     end' \
  "$GLOBAL_SETTINGS_JSON" >"$TEMP_SETTINGS" && mv "$TEMP_SETTINGS" "$GLOBAL_SETTINGS_JSON"

echo "--- 6. Finalizing ---"
echo "-------------------------------------------------------"
echo "Setup complete."
echo ""
echo "  Extension: $EXT_NAME (launched via npx, no local build)"
echo "  Agents:    .gemini/agents/"
echo "  Hook:      $HOOK_SCRIPT"
echo ""
echo "If you are upgrading an existing vault from v1, you MUST rebuild the RAG"
echo "index once — see MIGRATION.md. A mixed old/new index degrades search"
echo "ranking silently, with no error."
echo "-------------------------------------------------------"
